<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6AKTRL2" failures="2" tests="8" name="Default test" time="23.864" errors="0" timestamp="2023-02-06T02:16:22 CET">
  <testcase classname="com.hopin.HopIn.services.RideServiceTest" name="shouldAcceptRide" time="0.113"/>
  <testcase classname="com.hopin.HopIn.services.RideServiceTest" name="shouldDeleteFavoriteRideForExistingId" time="0.039"/>
  <testcase classname="com.hopin.HopIn.services.RideServiceTest" name="shouldGetRideForExistingId" time="0.004"/>
  <testcase classname="com.hopin.HopIn.services.RideServiceTest" name="shouldStartRideForExistingRideWithStatusAccepted" time="0.005"/>
  <testcase classname="com.hopin.HopIn.services.RideServiceTest" name="shouldThrowExceptionForAcceptingRideWithBadStatus" time="0.016">
    <failure type="org.testng.TestException" message="
Method RideServiceTest.shouldThrowExceptionForAcceptingRideWithBadStatus()[pri:0, instance:com.hopin.HopIn.services.RideServiceTest@7e3f95fe] should have thrown an exception of type class org.springframework.web.server.ResponseStatusException">
      <![CDATA[org.testng.TestException: 
Method RideServiceTest.shouldThrowExceptionForAcceptingRideWithBadStatus()[pri:0, instance:com.hopin.HopIn.services.RideServiceTest@7e3f95fe] should have thrown an exception of type class org.springframework.web.server.ResponseStatusException
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:866)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:727)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- shouldThrowExceptionForAcceptingRideWithBadStatus -->
  <testcase classname="com.hopin.HopIn.services.RideServiceTest" name="shouldThrowExceptionForAcceptingRideWithNonExistingId" time="0.013">
    <failure type="org.testng.TestException" message="
Method RideServiceTest.shouldThrowExceptionForAcceptingRideWithNonExistingId()[pri:0, instance:com.hopin.HopIn.services.RideServiceTest@7e3f95fe] should have thrown an exception of type class org.springframework.web.server.ResponseStatusException">
      <![CDATA[org.testng.TestException: 
Method RideServiceTest.shouldThrowExceptionForAcceptingRideWithNonExistingId()[pri:0, instance:com.hopin.HopIn.services.RideServiceTest@7e3f95fe] should have thrown an exception of type class org.springframework.web.server.ResponseStatusException
at org.testng.internal.invokers.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:81)
at org.testng.internal.invokers.TestInvoker.considerExceptions(TestInvoker.java:866)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:727)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- shouldThrowExceptionForAcceptingRideWithNonExistingId -->
  <testcase classname="com.hopin.HopIn.services.RideServiceTest" name="shouldThrowExceptionForNonExistingFavoriteRideId" time="0.006"/>
  <testcase classname="com.hopin.HopIn.services.RideServiceTest" name="shouldThrowExceptionForNonExistingRideId" time="0.002"/>
</testsuite> <!-- Default test -->
